version: "3"

services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8099:80
    restart: unless-stopped
    volumes:
      - ~/docker-data/heimdall:/config
